# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 16-12-2015 01:53
buildfase:
  stage: build
  script:
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g')
    - mvn clean install
    - mkdir -p ../dist
    - cp target/$1.jar ../dist/$1.jar
  only:
  - master
distributefase:
  stage: deploy
  script:
# Set variable $1 as the jar name
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g').jar
# Sudo su
    - "echo $gitcipass|sudo -S bash"
# Copy files to there locations
    - "sudo cp -f ../dist/$1 /home/minecraft/multicraft/servers/server3/plugins/update"
stages:
  - build
  - deploy