name: HubTweaks
main: nl.imine.hubtweaks.HubTweaks
version: fc8554b

depend: [iMine_Statistics, iMineAPI]
commands:
  HubTweaks:
    description: Default command for anything in this plugin.
    usage: /HubTweaks
  kotl:
    description: Default command for kingdom of the ladder.
    usage: /kotl